name: Tests

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: |
    ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install .[dev]

      - name: Type checking
        run: mypy giraph
